# Generated by Django 4.2.7 on 2023-12-04 14:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('create', models.DateTimeField(default=datetime.datetime.now)),
                ('type_transaction', models.CharField(max_length=255)),
                ('account_received', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_received', to='account.account')),
                ('account_sent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_sent', to='account.account')),
                ('card', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='card', to='card.card')),
            ],
        ),
    ]
