# Generated by Django 4.2.7 on 2023-11-24 17:16

import cpf_field.models
import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('cpf', cpf_field.models.CPFField(default='', max_length=14, unique=True, verbose_name='cpf')),
                ('url_image', models.ImageField(null=True, upload_to=user.models.user_image_field)),
                ('password', models.CharField(max_length=255)),
                ('declared_salary', models.FloatField(default=0.0, null=True)),
                ('last_try_login', models.DateTimeField(default=datetime.datetime.now)),
                ('count_try_login', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_account', models.CharField(max_length=10, unique=True)),
                ('agency', models.CharField(max_length=4)),
                ('balance', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('cvv', models.CharField(max_length=3)),
                ('due_data', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('type_card', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valueTotal', models.FloatField()),
                ('fees', models.DecimalField(decimal_places=4, max_digits=5)),
                ('numberTotalParcels', models.IntegerField()),
                ('approved', models.BooleanField(default=True)),
                ('observation', models.CharField(max_length=255)),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.card')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valueLoan', models.FloatField()),
                ('fees', models.DecimalField(decimal_places=4, max_digits=5)),
                ('numberTotalParcels', models.IntegerField()),
                ('approved', models.BooleanField(default=True)),
                ('observation', models.CharField(max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.account')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('description', models.CharField(max_length=255)),
                ('type_transaction', models.CharField(max_length=255)),
                ('account_received', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_received', to='user.account')),
                ('account_sent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_sent', to='user.account')),
            ],
        ),
        migrations.CreateModel(
            name='LoanParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberParcels', models.IntegerField()),
                ('value_parcel', models.FloatField()),
                ('due_date', models.DateField()),
                ('value_paid', models.FloatField()),
                ('paid_date', models.DateField()),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.loan')),
            ],
        ),
        migrations.CreateModel(
            name='CreditParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberParcels', models.IntegerField()),
                ('value_parcel', models.FloatField()),
                ('due_date', models.DateField()),
                ('value_paid', models.FloatField()),
                ('paid_date', models.DateField()),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.credit')),
            ],
        ),
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('neighborhood', models.CharField(blank=True, max_length=255)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('number', models.IntegerField()),
                ('cep', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
