# Generated by Django 4.2.7 on 2023-11-14 18:38

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='url_image',
            field=models.ImageField(null=True, upload_to=user.models.user_image_field),
        ),
    ]
