# Generated by Django 4.2.7 on 2023-11-27 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_transaction_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account_sent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_sent', to='user.account'),
        ),
    ]
