# Generated by Django 4.2.7 on 2023-11-17 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('description', models.CharField(max_length=255)),
                ('account_received', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_received', to='user.account')),
                ('account_sent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_sent', to='user.account')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('cvv', models.CharField(max_length=3)),
                ('validate_data', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('type_card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.typetransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
