# Generated by Django 4.2.7 on 2023-11-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_transaction_account_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='due_data',
            field=models.DateTimeField(),
        ),
    ]
