# Generated by Django 4.2.7 on 2023-11-17 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_typetransaction_transaction_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valueTotal', models.FloatField()),
                ('fees', models.DecimalField(decimal_places=4, max_digits=5)),
                ('numberTotalParcels', models.IntegerField()),
                ('approved', models.BooleanField(default=True)),
                ('observation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valueLoan', models.FloatField()),
                ('fees', models.DecimalField(decimal_places=4, max_digits=5)),
                ('numberTotalParcels', models.IntegerField()),
                ('approved', models.BooleanField(default=True)),
                ('observation', models.CharField(max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.account')),
            ],
        ),
        migrations.CreateModel(
            name='TypeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_card', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='card',
            old_name='validate_data',
            new_name='due_data',
        ),
        migrations.CreateModel(
            name='LoanParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberParcels', models.IntegerField()),
                ('value_parcel', models.FloatField()),
                ('due_date', models.DateField()),
                ('value_paid', models.FloatField()),
                ('paid_date', models.DateField()),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.loan')),
            ],
        ),
        migrations.CreateModel(
            name='CreditParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberParcels', models.IntegerField()),
                ('value_parcel', models.FloatField()),
                ('due_date', models.DateField()),
                ('value_paid', models.FloatField()),
                ('paid_date', models.DateField()),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.credit')),
            ],
        ),
        migrations.AddField(
            model_name='credit',
            name='credit_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.card'),
        ),
        migrations.AlterField(
            model_name='card',
            name='type_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.typecard'),
        ),
    ]
