# Generated by Django 4.2.7 on 2023-12-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_card_due_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditparcel',
            old_name='numberParcels',
            new_name='numberParcel',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='fees',
        ),
        migrations.AddField(
            model_name='credit',
            name='numberPayedParcels',
            field=models.IntegerField(default=0),
        ),
    ]
