# Generated by Django 4.2.7 on 2023-11-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_adress_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='cep',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='adress',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='adress',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='adress',
            name='state',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='adress',
            name='street',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='adress',
            name='uf',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
