# Generated by Django 4.2.7 on 2023-12-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_numberparcels_creditparcel_numberparcel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='observation',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
