# Generated by Django 4.2.7 on 2023-11-19 15:48

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_adress_cep_alter_adress_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=cpf_field.models.CPFField(default='', max_length=14, unique=True, verbose_name='cpf'),
        ),
    ]
