# Generated by Django 4.2.7 on 2023-12-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_credit_observation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditparcel',
            old_name='numberParcel',
            new_name='number_parcel',
        ),
        migrations.RemoveField(
            model_name='loanparcel',
            name='value_paid',
        ),
        migrations.AddField(
            model_name='loanparcel',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loanparcel',
            name='paid_date',
            field=models.DateField(default=None),
        ),
    ]
