# Generated by Django 4.2.7 on 2023-12-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_rename_numberparcel_creditparcel_number_parcel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditparcel',
            name='value_paid',
        ),
        migrations.AddField(
            model_name='creditparcel',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='creditparcel',
            name='paid_date',
            field=models.DateField(default=None),
        ),
    ]
