# Generated by Django 4.2.7 on 2023-11-22 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_adress_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='count_try_login',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='last_try_login',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
