# Generated by Django 4.2.7 on 2023-12-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_creditparcel_value_paid_creditparcel_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditparcel',
            name='paid_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
