# Generated by Django 4.2.7 on 2023-12-02 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_creditparcel_paid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='account_received',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.account'),
        ),
    ]
