# Generated by Django 4.2.7 on 2023-12-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_credit_account_received'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanparcel',
            old_name='numberParcels',
            new_name='number_parcel',
        ),
        migrations.AddField(
            model_name='loan',
            name='numberPayedParcels',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loan',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
