# Generated by Django 4.2.7 on 2023-12-03 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_rename_numberparcels_loanparcel_number_parcel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='fees',
        ),
    ]
