# Generated by Django 4.2.7 on 2023-12-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_remove_loan_approved_remove_loan_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanparcel',
            name='paid_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
