# Generated by Django 4.2.7 on 2023-12-04 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_loanparcel_paid_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='card',
            name='user',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='account_received',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='credit_card',
        ),
        migrations.RemoveField(
            model_name='creditparcel',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='account',
        ),
        migrations.RemoveField(
            model_name='loanparcel',
            name='loan',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account_received',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account_sent',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='card',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Adress',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Credit',
        ),
        migrations.DeleteModel(
            name='CreditParcel',
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
        migrations.DeleteModel(
            name='LoanParcel',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
